// test api
GET http://localhost:5000/

###

// create record
POST http://localhost:5000/api/v1/todo
Content-Type: application/json

{
    "record": "test5"
}


###
// get all the records
GET http://localhost:5000/api/v1/todo

###
