// test api
GET http://localhost:5000/

###

// create todo
POST http://localhost:5000/api/v1/todo
Content-Type: application/json

{
    "record": "test5"
}


###
// get all the todos
GET http://localhost:5000/api/v1/todo

###
// get specific todo
GET http://localhost:5000/api/v1/todo/test2


###
// update todo
PATCH http://localhost:5000/api/v1/todo/test
Content-Type: application/json

{
    "newRecord": "test1"
}

###
DELETE http://localhost:5000/api/v1/todo/test2


###

// user routes

POST http://localhost:5000/api/v1/users/signup
Content-Type: application/json

{
    "firstName": "Kalidass",
    "lastName": "Boopathi",
    "email": "kalidass@email.com",
    "password": "kalidass123"
}